import React from 'react'
import { BrowserRouter, Routes, Route, Link, useParams } from 'react-router-dom'
import { initializeApp } from 'firebase/app'
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth'
import './styles.css'
import { firebaseConfig } from './firebaseConfig'
import { loadBooks, saveBook } from './firebase'
import { recent, queue, departures, allBooks, detailData } from './data'

const app = initializeApp(firebaseConfig)
const auth = getAuth(app)

function BookCover({ label, small, muted }) { return <div className={`bookCover ${small ? 'small' : ''} ${muted ? 'mutedCover' : ''}`}>{label}</div> }
function Header() { return <div className="titleRow"><span className="ornament" /><h1 className="siteTitle">Benedict Library</h1><span className="ornament" /></div> }
function Shell({ children, user, onLogout }) { return <div className="page"><Header />{user ? <div className="topBar"><span>Signed in as {user.email}</span><button className="ghostBtn" onClick={onLogout}>Sign out</button></div> : null}{children}</div> }
function Home({ user, onLogout }) { return (<Shell user={user} onLogout={onLogout}>
  <section className="panel hero"><BookCover label="Benedict Library" /><div className="heroText"><div className="kicker">On the Desk.</div><h2>Benedict Library</h2><p>Sign in and begin building the collection.</p></div><button className="primaryBtn">Log Progress</button></section>
  <section className="plaqueGrid"><Link to="/stacks" className="plaque linkCard"><h3>The Stacks.</h3><div className="count">Physical Volumes</div><p>Active physical holdings, on shelves or on loan.</p></Link><Link to="/archives" className="plaque linkCard"><h3>The Archives.</h3><div className="count">Digital Volumes</div><p>Cataloged ebooks and audiobooks.</p></Link></section>
  <section className="middleGrid"><Link to="/circulation" className="panel linkCard"><h3>The Circulation Desk</h3><p className="emptyState">No circulation records yet.</p></Link><Link to="/reading-ledger" className="panel linkCard"><h3>Recently Cataloged</h3><p className="emptyState">No books have been cataloged yet.</p><h3 className="queueTitle">The Queue</h3><p className="emptyState">No queue items yet.</p></Link></section>
  <section className="bottomGrid"><Link to="/departures" className="panel linkCard"><h3>The Ledger of Departures</h3><p className="emptyState">No departures recorded yet.</p></Link><Link to="/reading-ledger" className="panel linkCard timeline"><h3>The Annals</h3><div className="timelineBlock"><p className="emptyState">No completed reads yet.</p></div></Link></section>
  <footer className="footerLinks"><Link to="/catalog">Detailed Catalog</Link></footer>
</Shell>) }
function BookCard({ item, onEdit }) { return <div className="detailCardWrap"><Link to={`/book/${encodeURIComponent(item.title)}`} className="detailCard"><div className="detailCover"><BookCover label={item.title} small /></div><div className="detailMeta"><h4>{item.title}</h4><div className="author">{item.author}</div><div className="tags">{(item.tags || []).map(t => <span key={t}>{t}</span>)}</div></div></Link><button className="ghostBtn editBtn" onClick={() => onEdit(item)}>Edit</button></div> }
function InventoryPage({ title, subtitle, items, hero, user, onLogout, onEdit }) { const [query, setQuery] = React.useState(''); const filtered = items.filter(i => `${i.title} ${i.author} ${(i.tags || []).join(' ')}`.toLowerCase().includes(query.toLowerCase())); return <Shell user={user} onLogout={onLogout}><div className="pageView"><Link className="backLink" to="/">← Back</Link><h2 className="pageTitle">{title}</h2><p className="pageSubtitle">{subtitle}</p>{hero}<div className="searchBar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles, authors, tags..." /></div><div className="detailList">{filtered.length ? filtered.map(item => <BookCard key={item.title} item={item} onEdit={onEdit || (() => {})} />) : <p className="emptyState">No items yet.</p>}</div></div></Shell> }
function StacksPage({ user, onLogout }) { return <InventoryPage title="The Stacks" subtitle="Physical holdings with locations, tags, and ownership details." items={[]} hero={<div className="inventoryHero"><div className="inventoryStat"><div className="statLabel">Physical Volumes</div><div className="statValue">0</div></div><div className="inventoryStat"><div className="statLabel">On Loan</div><div className="statValue">0</div></div><div className="inventoryStat"><div className="statLabel">Signed</div><div className="statValue">0</div></div></div>} user={user} onLogout={onLogout} /> }
function ArchivesPage({ user, onLogout }) { return <InventoryPage title="The Archives" subtitle="Digital holdings and future local-file support." items={[]} hero={<div className="inventoryHero"><div className="inventoryStat"><div className="statLabel">Digital Volumes</div><div className="statValue">0</div></div><div className="inventoryStat"><div className="statLabel">Audiobooks</div><div className="statValue">0</div></div><div className="inventoryStat"><div className="statLabel">Local Files</div><div className="statValue">0</div></div></div>} user={user} onLogout={onLogout} /> }
function CirculationPage({ user, onLogout }) { return <InventoryPage title="The Circulation Desk" subtitle="Books currently out on loan and active circulation status." items={[]} hero={<div className="inventoryHero"><div className="inventoryStat"><div className="statLabel">Out on Loan</div><div className="statValue">0</div></div><div className="inventoryStat"><div className="statLabel">Due This Week</div><div className="statValue">0</div></div><div className="inventoryStat"><div className="statLabel">Borrowers</div><div className="statValue">0</div></div></div>} user={user} onLogout={onLogout} /> }
function ReadingLedgerPage({ user, onLogout }) { return <Shell user={user} onLogout={onLogout}><div className="pageView"><Link className="backLink" to="/">← Back</Link><h2 className="pageTitle">The Reading Ledger</h2><p className="pageSubtitle">Queue, currently reading, and completed reading annals.</p><div className="ledgerGrid"><section className="ledgerPanel"><div className="panelTop"><h3>The Queue</h3><div className="panelPill">0 books</div></div><p className="emptyState">No queue items yet.</p></section><section className="ledgerPanel deskPanel"><div className="panelTop"><h3>On the Desk</h3><div className="panelPill">Current read</div></div><p className="emptyState">No current read yet.</p></section><section className="ledgerPanel annalsPanel"><div className="panelTop"><h3>The Annals</h3><div className="panelPill">Yearly timeline</div></div><div className="timelineBlock"><p className="emptyState">No completed reads yet.</p></div></section></div></div></Shell> }
function DeparturesPage({ user, onLogout }) { return <Shell user={user} onLogout={onLogout}><div className="pageView"><Link className="backLink" to="/">← Back</Link><h2 className="pageTitle">The Ledger of Departures</h2><p className="pageSubtitle">Books that left the collection permanently.</p><div className="departuresGrid"><p className="emptyState">No departures recorded yet.</p></div></div></Shell> }
function CatalogEditor({ onSave, editing, setEditing }) { const [form, setForm] = React.useState({ title: '', author: '', status: 'Owned - Physical', location: 'Unassigned', tags: '', provenance: '', reading: '', ownership: '', cataloged: '' }); React.useEffect(() => { if (editing) setForm({ title: editing.title || '', author: editing.author || '', status: editing.status || 'Owned - Physical', location: editing.location || 'Unassigned', tags: (editing.tags || []).join(', '), provenance: editing.provenance || '', reading: editing.reading || '', ownership: editing.ownership || '', cataloged: editing.cataloged || '' }) }, [editing]); const submit = async (e) => { e.preventDefault(); await onSave({ ...form, tags: form.tags.split(',').map(s => s.trim()).filter(Boolean) }); setForm({ title: '', author: '', status: 'Owned - Physical', location: 'Unassigned', tags: '', provenance: '', reading: '', ownership: '', cataloged: '' }); setEditing(null) }; return <form className="editorPanel" onSubmit={submit}><div className="editorHeader"><h3>{editing ? 'Edit Book' : 'Add Book'}</h3><button type="button" className="ghostBtn" onClick={() => setEditing(null)}>Clear</button></div><div className="editorGrid"><input placeholder="Title" value={form.title} onChange={e=>setForm({...form, title:e.target.value})} /><input placeholder="Author" value={form.author} onChange={e=>setForm({...form, author:e.target.value})} /><input placeholder="Status" value={form.status} onChange={e=>setForm({...form, status:e.target.value})} /><input placeholder="Location" value={form.location} onChange={e=>setForm({...form, location:e.target.value})} /><input placeholder="Cataloged date" value={form.cataloged} onChange={e=>setForm({...form, cataloged:e.target.value})} /><input className="wide" placeholder="Tags, comma separated" value={form.tags} onChange={e=>setForm({...form, tags:e.target.value})} /><textarea className="wide" placeholder="Provenance" value={form.provenance} onChange={e=>setForm({...form, provenance:e.target.value})} /><textarea className="wide" placeholder="Reading log" value={form.reading} onChange={e=>setForm({...form, reading:e.target.value})} /><textarea className="wide" placeholder="Ownership notes" value={form.ownership} onChange={e=>setForm({...form, ownership:e.target.value})} /></div><button className="primaryBtn" type="submit">Save Book</button></form> }
function CatalogPage({ user, onLogout }) { const [editing, setEditing] = React.useState(null); const [catalog, setCatalog] = React.useState([]); const [loading, setLoading] = React.useState(true); React.useEffect(() => { (async () => { try { const remote = await loadBooks(); setCatalog(remote || []) } catch (e) { setCatalog([]) } finally { setLoading(false) } })() }, []); const handleSave = async (book) => { await saveBook(book); const remote = await loadBooks(); setCatalog(remote || []) }; return <Shell user={user} onLogout={onLogout}><div className="pageView"><Link className="backLink" to="/">← Back</Link><h2 className="pageTitle">Detailed Catalog</h2><p className="pageSubtitle">A complete inventory view of the collection.</p><CatalogEditor onSave={handleSave} editing={editing} setEditing={setEditing} /><div className="searchBar"><input placeholder="Search the full catalog..." /></div>{loading ? <p>Loading catalog…</p> : <div className="detailList">{catalog.length ? catalog.map(item => <BookCard key={item.id || item.title} item={item} onEdit={setEditing} />) : <p className="emptyState">No books yet. Add your first title above.</p>}</div>}</div></Shell> }
function BookPage({ user, onLogout }) { const { title } = useParams(); const decoded = decodeURIComponent(title || ''); const item = detailData[decoded] || { author: 'Unknown Author', status: 'Inventory Item', location: 'Unassigned', cataloged: 'Unknown', provenance: 'No notes yet.', reading: 'No reading log available.', ownership: 'Ownership details pending.' }; return <Shell user={user} onLogout={onLogout}><div className="pageView"><Link className="backLink" to="/">← Back</Link><div className="bookHero"><BookCover label={decoded || 'Book'} /><div className="bookHeroText"><h2 className="pageTitle">{decoded}</h2><div className="author bookHeroAuthor">{item.author}</div><div className="tags"><span>{item.status}</span><span>{item.location}</span></div><div className="bookMetaGrid"><div><span>Status</span><strong>{item.status}</strong></div><div><span>Location</span><strong>{item.location}</strong></div><div><span>Cataloged</span><strong>{item.cataloged}</strong></div></div></div></div><div className="bookDetailSections"><section className="bookDetailSection"><h3>Provenance</h3><p>{item.provenance || 'No provenance yet.'}</p></section><section className="bookDetailSection"><h3>Reading Log</h3><p>{item.reading || 'No reading log yet.'}</p></section><section className="bookDetailSection"><h3>Ownership</h3><p>{item.ownership || 'Ownership details pending.'}</p></section></div></div></Shell> }
export default function App() { const [user, setUser] = React.useState(null); const [email, setEmail] = React.useState(''); const [password, setPassword] = React.useState(''); const [loadingAuth, setLoadingAuth] = React.useState(true); React.useEffect(() => onAuthStateChanged(auth, u => { setUser(u); setLoadingAuth(false) }), []); const login = async (e) => { e.preventDefault(); await signInWithEmailAndPassword(auth, email, password) }; const logout = async () => { await signOut(auth) }; if (loadingAuth) return <div className="loginScreen"><div className="loginCard">Loading…</div></div>; if (!user) return <div className="loginScreen"><form className="loginCard" onSubmit={login}><h1 className="siteTitle">Benedict Library</h1><p>Sign in to manage the collection.</p><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} /><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} /><button className="primaryBtn" type="submit">Sign in</button></form></div>; return <BrowserRouter><Routes><Route path="/" element={<Home user={user} onLogout={logout} />} /><Route path="/stacks" element={<StacksPage user={user} onLogout={logout} />} /><Route path="/archives" element={<ArchivesPage user={user} onLogout={logout} />} /><Route path="/circulation" element={<CirculationPage user={user} onLogout={logout} />} /><Route path="/reading-ledger" element={<ReadingLedgerPage user={user} onLogout={logout} />} /><Route path="/departures" element={<DeparturesPage user={user} onLogout={logout} />} /><Route path="/catalog" element={<CatalogPage user={user} onLogout={logout} />} /><Route path="/book/:title" element={<BookPage user={user} onLogout={logout} />} /></Routes></BrowserRouter> }