import React from 'react'
import { BrowserRouter, Routes, Route, Link, useParams } from 'react-router-dom'
import './styles.css'
import { recent, queue, seedBooks, departures, allBooks, detailData } from './data'
import { loadBooks, saveBook } from './firebase'

function BookCover({ label, small, muted }) { return <div className={`bookCover ${small ? 'small' : ''} ${muted ? 'mutedCover' : ''}`}>{label}</div> }
function Header() { return <div className="titleRow"><span className="ornament" /><h1 className="siteTitle">Benedict Library</h1><span className="ornament" /></div> }
function Shell({ children }) { return <div className="page"><Header />{children}</div> }

function Home() { return (<Shell>
  <section className="panel hero"><BookCover label="Benedict Library" /><div className="heroText"><div className="kicker">On the Desk.</div><h2>Benedict Library</h2><p>Sign in and begin building the collection.</p></div><button className="primaryBtn">Log Progress</button></section>
  <section className="plaqueGrid"><Link to="/stacks" className="plaque linkCard"><h3>The Stacks.</h3><div className="count">142 Physical Volumes</div><p>Active physical holdings, on shelves or on loan.</p></Link><Link to="/archives" className="plaque linkCard"><h3>The Archives.</h3><div className="count">84 Digital Volumes</div><p>Cataloged ebooks and audiobooks.</p></Link></section>
  <section className="middleGrid"><Link to="/circulation" className="panel linkCard"><h3>The Circulation Desk</h3><p className="emptyState">No circulation records yet.</p></Link><Link to="/reading-ledger" className="panel linkCard"><h3>Recently Cataloged</h3><p className="emptyState">No books have been cataloged yet.</p><h3 className="queueTitle">The Queue</h3><p className="emptyState">No queue items yet.</p></Link></section>
  <section className="bottomGrid"><Link to="/departures" className="panel linkCard"><h3>The Ledger of Departures</h3><p className="emptyState">No departures recorded yet.</p></Link><Link to="/reading-ledger" className="panel linkCard timeline"><h3>The Annals</h3><div className="entry"><div className="year">2026</div><div>Finished The Left Hand of Darkness · Apr 18</div></div><div className="entry"><div className="year">2026</div><div>Finished Never Let Me Go · Mar 02</div></div><div className="entry"><div className="year">2025</div><div>Finished The Road · Dec 11</div></div></Link></section>
  <footer className="footerLinks"><Link to="/circulation">Circulation List</Link><Link to="/catalog">Detailed Catalog</Link><Link to="/departures">Past Departures</Link></footer>
</Shell>) }

function BookCard({ item, onEdit }) { return <div className="detailCardWrap"><Link to={`/book/${encodeURIComponent(item.title)}`} className="detailCard"><div className="detailCover"><BookCover label={item.title} small /></div><div className="detailMeta"><h4>{item.title}</h4><div className="author">{item.author}</div><div className="tags">{(item.tags || []).map(t => <span key={t}>{t}</span>)}</div></div></Link><button className="ghostBtn editBtn" onClick={() => onEdit(item)}>Edit</button></div> }
function InventoryPage({ title, subtitle, items, hero, onEdit }) { const [query, setQuery] = React.useState(''); const filtered = items.filter(i => `${i.title} ${i.author} ${(i.tags || []).join(' ')}`.toLowerCase().includes(query.toLowerCase())); return <Shell><div className="pageView"><Link className="backLink" to="/">← Back</Link><h2 className="pageTitle">{title}</h2><p className="pageSubtitle">{subtitle}</p>{hero}<div className="searchBar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles, authors, tags..." /></div><div className="detailList">{filtered.map(item => <BookCard key={item.title} item={item} onEdit={onEdit} />)}</div></div></Shell> }
function StacksPage() { return <InventoryPage title="The Stacks" subtitle="Physical holdings with locations, tags, and ownership details." items={[]} hero={<div className="inventoryHero"><div className="inventoryStat"><div className="statLabel">Physical Volumes</div><div className="statValue">142</div></div><div className="inventoryStat"><div className="statLabel">On Loan</div><div className="statValue">12</div></div><div className="inventoryStat"><div className="statLabel">Signed</div><div className="statValue">34</div></div></div>} /> }
function ArchivesPage() { return <InventoryPage title="The Archives" subtitle="Digital holdings and future local-file support." items={[]} hero={<div className="inventoryHero"><div className="inventoryStat"><div className="statLabel">Digital Volumes</div><div className="statValue">84</div></div><div className="inventoryStat"><div className="statLabel">Audiobooks</div><div className="statValue">19</div></div><div className="inventoryStat"><div className="statLabel">Local Files</div><div className="statValue">6</div></div></div>} /> }
function CirculationPage() { return <InventoryPage title="The Circulation Desk" subtitle="Books currently out on loan and active circulation status." items={[]} hero={<div className="inventoryHero"><div className="inventoryStat"><div className="statLabel">Out on Loan</div><div className="statValue">12</div></div><div className="inventoryStat"><div className="statLabel">Due This Week</div><div className="statValue">3</div></div><div className="inventoryStat"><div className="statLabel">Borrowers</div><div className="statValue">5</div></div></div>} /> }
function ReadingLedgerPage() { const [active, setActive] = React.useState('Moby Dick'); return <Shell><div className="pageView"><Link className="backLink" to="/">← Back</Link><h2 className="pageTitle">The Reading Ledger</h2><p className="pageSubtitle">Queue, currently reading, and completed reading annals.</p><div className="ledgerGrid"><section className="ledgerPanel"><div className="panelTop"><h3>The Queue</h3><div className="panelPill">4 books</div></div><div className="coverRow wrap largeQueue">{queue.map((q, i) => <button key={i} className={`queueThumb ${active === q ? 'active' : ''}`} onClick={() => setActive(q)}><BookCover label={q} small /></button>)}</div><div className="ledgerStats"><div><span>Queue</span><strong>4</strong></div><div><span>Reading</span><strong>1</strong></div><div><span>Completed</span><strong>18</strong></div></div></section><section className="ledgerPanel deskPanel"><div className="panelTop"><h3>On the Desk</h3><div className="panelPill">Current read</div></div><div className="deskBlock"><BookCover label={active} /><div><div className="kicker">Currently Reading</div><h4>{active}</h4><p>{detailData[active]?.reading || 'Private notes, quotes, and progress.'}</p><textarea placeholder="Write a note..." defaultValue={detailData[active]?.provenance || ''} /></div></div></section><section className="ledgerPanel annalsPanel"><div className="panelTop"><h3>The Annals</h3><div className="panelPill">Yearly timeline</div></div><div className="timelineBlock"><p className="emptyState">No completed reads yet.</p></div></section></div></div></Shell> }
function DeparturesPage() { return <Shell><div className="pageView"><Link className="backLink" to="/">← Back</Link><h2 className="pageTitle">The Ledger of Departures</h2><p className="pageSubtitle">Books that left the collection permanently.</p><div className="departuresGrid">{departures.map(d => <div key={d.title} className="departureCard"><BookCover label={d.tag} small muted /><div><h4>{d.title}</h4><p>{d.status}</p><div className="tags"><span>{d.tag}</span><span>Stamped</span></div></div></div>)}</div></div></Shell> }

function CatalogEditor({ onSave, editing, setEditing }) {
  const [form, setForm] = React.useState({ title: '', author: '', status: 'Owned - Physical', location: 'Unassigned', tags: '', provenance: '', reading: '', ownership: '' })
  React.useEffect(() => { if (editing) setForm({ ...editing, tags: (editing.tags || []).join(', ') }) }, [editing])
  const submit = (e) => { e.preventDefault(); onSave({ ...form, tags: form.tags.split(',').map(s => s.trim()).filter(Boolean) }); setForm({ title: '', author: '', status: 'Owned - Physical', location: 'Unassigned', tags: '', provenance: '', reading: '', ownership: '' }); }
  return <form className="editorPanel" onSubmit={submit}><div className="editorHeader"><h3>{editing ? 'Edit Book' : 'Add Book'}</h3><button type="button" className="ghostBtn" onClick={() => setEditing(null)}>Clear</button></div><div className="editorGrid"><input placeholder="Title" value={form.title} onChange={e=>setForm({...form, title:e.target.value})} /><input placeholder="Author" value={form.author} onChange={e=>setForm({...form, author:e.target.value})} /><input placeholder="Status" value={form.status} onChange={e=>setForm({...form, status:e.target.value})} /><input placeholder="Location" value={form.location} onChange={e=>setForm({...form, location:e.target.value})} /><input className="wide" placeholder="Tags, comma separated" value={form.tags} onChange={e=>setForm({...form, tags:e.target.value})} /><textarea className="wide" placeholder="Provenance" value={form.provenance} onChange={e=>setForm({...form, provenance:e.target.value})} /><textarea className="wide" placeholder="Reading log" value={form.reading} onChange={e=>setForm({...form, reading:e.target.value})} /><textarea className="wide" placeholder="Ownership notes" value={form.ownership} onChange={e=>setForm({...form, ownership:e.target.value})} /></div><button className="primaryBtn" type="submit">Save Book</button></form>
}

function CatalogPage() {
  const [editing, setEditing] = React.useState(null)
  const [catalog, setCatalog] = React.useState(allBooks)
  const [loading, setLoading] = React.useState(true)
  React.useEffect(() => { (async () => { try { const remote = await loadBooks(); if (remote?.length) setCatalog(remote); } catch (e) {} finally { setLoading(false) } })() }, [])
  const handleSave = async (book) => { await saveBook(book); const remote = await loadBooks(); setCatalog(remote.length ? remote : catalog); setEditing(null) }
  return <Shell><div className="pageView"><Link className="backLink" to="/">← Back</Link><h2 className="pageTitle">Detailed Catalog</h2><p className="pageSubtitle">A complete inventory view of the collection.</p><CatalogEditor onSave={handleSave} editing={editing} setEditing={setEditing} /><div className="searchBar"><input placeholder="Search the full catalog..." /></div>{loading ? <p>Loading catalog…</p> : <div className="detailList">{catalog.length ? catalog.map(item => <BookCard key={item.id || item.title} item={item} onEdit={setEditing} />) : <p className="emptyState">No books yet. Add your first title above.</p>}</div>}</div></Shell>
}
function BookPage() { const { title } = useParams(); const decoded = decodeURIComponent(title || ''); const item = detailData[decoded] || { author: 'Unknown Author', status: 'Inventory Item', location: 'Unassigned', cataloged: 'Unknown', provenance: 'No notes yet.', reading: 'No reading log available.', ownership: 'Ownership details pending.' }; return <Shell><div className="pageView"><Link className="backLink" to="/">← Back</Link><div className="bookHero"><BookCover label={decoded || 'Book'} /><div className="bookHeroText"><h2 className="pageTitle">{decoded}</h2><div className="author bookHeroAuthor">{item.author}</div><div className="tags"><span>{item.status}</span><span>{item.location}</span></div><div className="bookMetaGrid"><div><span>Status</span><strong>{item.status}</strong></div><div><span>Location</span><strong>{item.location}</strong></div><div><span>Cataloged</span><strong>{item.cataloged}</strong></div></div></div></div><div className="bookDetailSections"><section className="bookDetailSection"><h3>Provenance</h3><p>{item.provenance || 'No provenance yet.'}</p></section><section className="bookDetailSection"><h3>Reading Log</h3><p>{item.reading || 'No reading log yet.'}</p></section><section className="bookDetailSection"><h3>Ownership</h3><p>{item.ownership || 'Ownership details pending.'}</p></section></div></div></Shell> }
export default function App() { return <BrowserRouter><Routes><Route path="/" element={<Home />} /><Route path="/stacks" element={<StacksPage />} /><Route path="/archives" element={<ArchivesPage />} /><Route path="/circulation" element={<CirculationPage />} /><Route path="/reading-ledger" element={<ReadingLedgerPage />} /><Route path="/departures" element={<DeparturesPage />} /><Route path="/catalog" element={<CatalogPage />} /><Route path="/book/:title" element={<BookPage />} /></Routes></BrowserRouter> }
